### PR TITLE
Improve python tools

### PR DESCRIPTION
**Pull request by tntexplosivesltd**
* Use `with` statement for file access
* Use f-strings instead of modulo string formatting
* Single quotes in most places

Unfortunately I am not able to test this, I don't have a copy of Lego Island and I can't get any output asm files to test with. I am also using Linux.

Is there any easy way for me to test this? I plan on improving these python tools

### CODE REVIEW

**Comment by foxtacles** [comment]
> Is there any easy way for me to test this? I plan on improving these python tools

Hi! Try to replicate the workflow specified in the build action: https://github.com/isledecomp/isle/blob/master/.github/workflows/build.yml This should also work on Linux. A copy of LEGO Island is not required (although a few files from it, but you can obtain them the same way the build script gets them).

**Comment by tntexplosivesltd** [comment]
Okay I managed to get everything building and the scripts run now.
Had to get it working under Windows

**Comment by foxtacles** [comment]
Looking at the output of `reccmp`, I think `can_resolve_register_differences` appears to be broken since it no longer recognizes the "100%*" matches.

Also rounding the final accuracy metric to show 2 digits would look better (as it was before):

`Total effective accuracy 56.33056831607717%`

**Comment by tntexplosivesltd** [comment]
Ah oops found my mistake 😄 have fixed it now

**Pull request merged**
