### PR TITLE
MxPalette header

### PR DESCRIPTION
**Pull request by ItzSwirlz**
i can implement these but i dont want to run too ahead of myself..

also: CRLF or LF line endings

### CODE REVIEW

**Comment by itsmattkc** [comment]
I'm afraid this isn't correct:

- Members should not have the name of the class (`MxPalette::`). This will throw a compiler error.
- The `__cdecl` keyword is unnecessary (it's the default anyway).
- These should be marked as `__declspec(dllexport)`.
- The `operator==` function actually takes a `MxPalette &` parameter instead of `MxPalette *` (they're equivalent in assembly but not in C++)

**Comment by ItzSwirlz** [comment]
Hmm... i was able to build it just fine. I'll apply your suggestions, thanks for helping me!

**Comment by itsmattkc** [comment]
> Hmm... i was able to build it just fine.

Looks like Visual Studio permits "extra qualifications on members", but it's against standard and GCC/Clang will throw an error (unless `-fpermissive` is used).

Thinking about it, I might actually write a script to automatically convert the LEGO1 exports into headers. That'd probably be faster than doing them all manually, and could then be reused in future decomps of Windows games. Thanks for the submission though!

**Comment by itsmattkc** [comment]
All LEGO1 exports have now been added to the code in 279d62627909b6253bc115c77adb96413637ca27

**Pull request closed without merging**
