### PR TITLE
reccmp: template compare annotations

### PR DESCRIPTION
**Pull request by BranDougherty**
Adds the ability to compare non-inlined instantiations of template functions to reccmp. This could potentially be used to compare STL versions (although the MSVC420 version seems like a match so far), and other template classes like `MxPtrList`.

Usage:
```
// OFFSET: LEGO1 0x100ac320 TEMPLATE
// list<unsigned int,allocator<unsigned int> >::~list<unsigned int,allocator<unsigned int> >
```

I've checked the "Allow edits by maintainers" box please remove the example code before merging.

### CODE REVIEW

**Comment by foxtacles** [comment]
I'm going to give this a try soon on real code, I think with `MxList` we have a good test case where we should be able to compare the non-inlined destructors of the various instantiations.

**Review by foxtacles — APPROVED** [review]
I've added template compare annotations for instances of `MxList`. Looks good to me. I think this is useful and will be even more so since I'm seeing more templated stuff coming up soon. What do you think @itsmattkc?

**Comment by itsmattkc** [comment]
Yeah I think it's a good idea. If it all works, I'd be happy to merge.

**Comment by foxtacles** [comment]
> If it all works, I'd be happy to merge.

Works correctly as far as I can tell, if you could double check it that would be great since it touches reccmp.

**Pull request merged**
