### PR TITLE
lego1: implement more of LegoNavController

### PR DESCRIPTION
**Pull request by foxtacles**
I've added a few more functions:

* `SetTargets`, `CalculateNewTargetSpeed`, `CalculateNewAccel` are completed and match the original assembly
* LegoNavController ctor - implemented and matching except for the `InputManager` bit
* LegoNavController dtor - depends on `InputManager`, see ctor above, commented out for now
* Added `Timer()`, also see https://github.com/isledecomp/isle/pull/17
* `SetControlMax` - depends on `VideoManager`, only checks a single attribute/flag of it though, commented out for now

### CODE REVIEW

**Comment by foxtacles** [comment]
@itsmattkc fixed the merge conflict

**Comment by itsmattkc** [comment]
I see you still committing to this. Let me know when it's done and ready for review.

**Comment by foxtacles** [comment]
> I see you still committing to this. Let me know when it's done and ready for review.

It's done now

**Comment by itsmattkc** [comment]
I've introduced a new syntax for functions so my script can compare with the original assembly. Can you add those to the new functions you've implemented here? The syntax is:

```
// OFFSET: LEGO1 <address>
```

...above the function definition. You can see examples in the `master` branch. Also can you comment the address of the static variables you added?

**Pull request merged**
