### PR TITLE
Implement Score

### PR DESCRIPTION
**Pull request by tahg**
As this is my first contribution, I don't know if it's suitable to be pulled as is.  I would appreciate feedback if there's any overall style issues I should fix.
There are two functions still with significant issues for bytecode, Score::Paint, and Score::FillRect. A few others have some minor issues with using different registers or stack locations, but I don't know how to fix those.

### CODE REVIEW

**Comment by foxtacles** [comment]
Looks like great work, thank you!

Is there any chance you could break this down into smaller PRs? It's fine if they depend on each other, but it would make the review a fair bit easier. If you think that isn't feasible, I will start reviewing this one but it will take some time.

With regards to the code style, it mostly looks good. Unfortunately we don't have a linter/comprehensive style guide yet (except for the few rules in [CONTRIBUTING.md](https://github.com/isledecomp/isle/blob/master/CONTRIBUTING.md) but I can see you made an effort to stick to the (mostly unwritten) existing style as much as possible, which I appreciate.

**Comment by tahg** [comment]
I understand that it make take some time to review, but I'm not sure I'm good enough with git to split it up at this point.  I'll have to remember that a whole class is probably too much in the future.

**Comment by tahg** [comment]
Fixed a logical issue in DeleteObjects. It's still unfortunately not quite byte accurate.

**Comment by foxtacles** [comment]
* Added `DECOMP_SIZE_ASSERT` for various classes
* Matched `DeleteObjects` to 100%
* Matched `PizzaMissionState::GetState` to 100%
* Matched `RaceState::GetState` to 100%
* Added missing vtable stubs
* Minor style fixes

There's one bug with the structure of `RaceState` since the decomp size assert fails. I've commented it out for now. Feel free to submit a fix in another PR. Thank you!

**Comment by tahg** [comment]
Line 42 should be undefined2, or undefined [2]. Technically it's a DWORD alignment, but idk what the packing settings are for MSVC.

**Comment by foxtacles** [comment]
> Line 42 should be undefined2, or undefined [2]. Technically it's a DWORD alignment, but idk what the packing settings are for MSVC.

Not sure which file you are referring to, but if you could submit another PR with a fix that would be great.

**Pull request merged**
