### PR TITLE
implement/match MxTransitionManager::Transition_Windows()

### PR DESCRIPTION
**Pull request by Ramen2X**
Implements MxTransitionManager::Transition_Windows().

~~Currently only a 60.33% match. I've been messing around with the function for a couple of hours but I can't really seem to get anywhere in terms of improving the match. It would be great to have a second set of eyes on this.~~

Edit: 100% match now due to a couple of contributions.

### CODE REVIEW

**Comment by Ramen2X** [comment]
Sorry - I need to rebase really quick.

**Comment by Ramen2X** [comment]
Okay fixed - sorry about that. I should have switched branches, but I intended to submit both of these functions in one PR and completely forgot.

**Comment by foxtacles** [comment]
Hm yeah, reversing that kind of arithmetic is a hassle since the instructions are also heavily influenced by the signedness of the values. I gave it a try but didn't get far either.

**Comment by disinvite** [comment]
@Ramen2X I sent you a PR that gets this a little closer.

**Comment by Ramen2X** [comment]
This now matches 75.5% thanks to the work of @disinvite. It could be entirely possible the rest is just MSVC entropy, but I'm unsure.

**Comment by Ramen2X** [comment]
Now matching, thanks to @itsmattkc.

**Comment by foxtacles** [comment]
Oh nice!

**Review by foxtacles — APPROVED** [review]

**Pull request merged**
