### PR TITLE
Add progress bar to README.md

### PR DESCRIPTION
**Pull request by AverseABFun-windows**
Just change the number at the end of the URL to the percentage

Also I'm working on figuring out a way to get Lego island running with wine as I have no windows computer(although I have a license and might just use a VM)

### CODE REVIEW

**Comment by itsmattkc** [comment]
Ahh thanks for showing how to do this. Only thing is I don't yet have a total number of functions so I can't calculate a percentage, but that shouldn't take long to get. I also wonder if there's a way to automate this, like maybe have a script on my VPS that periodically counts the number of functions in the repo and calculates the percentage.

> Also I'm working on figuring out a way to get Lego island running with wine as I have no windows computer(although I have a license and might just use a VM)

LEGO Island can be run in Wine. Just swap in the real D3DRM ([this one](https://legoisland.org/download/d3drm.zip) has the highest compatibility), and then use [Rebuilder](https://github.com/itsmattkc/legoislandrebuilder) to implement Pick()/GetPickRecords(), and it should all be playable.

**Comment by foxtacles** [comment]
> I also wonder if there's a way to automate this, like maybe have a script on my VPS that periodically counts the number of functions in the repo and calculates the percentage.

I was thinking about something similar: a percentage that would also factor in the accuracy of function implementations (measured by comparing the original with the decompilation assembly). That's probably quite a bit more work to implement but would be really cool to see imo.

**Comment by itsmattkc** [comment]
Yeah I'd love to have something like that. It would almost certainly take some time to set up, but there's probably stuff out there already that does the job that we can use. This for example seems to be automatically calculated: https://botw.link/progress

**Comment by msxrx** [comment]
Here's the script that's used for the progress; https://github.com/open-ead/nx-decomp-tools/blob/master/progress.py.

Per [this commit](https://github.com/zeldaret/botw/commit/9e3975a813baf0727f17f02cc1d7a17a15a30db9):
> Just like other decompilation projects, progress is tracked by looking at the percentage of decompiled bytes (the number of decompiled bytes divided by the total code size).

**Comment by foxtacles** [comment]
Quite interesting to see there are entire platforms like https://decomp.me/ with the aim to facilitate collaboration on decompilation! That being said, the entire ecosystem seems to be mostly focused around console games, so the tools might be of limited utility in our case...

**Comment by itsmattkc** [comment]
> Quite interesting to see there are entire platforms like https://decomp.me/ with the aim to facilitate collaboration on decompilation!

Oh yeah I've played around with that a little before, but yeah doesn't seem to be anything for x86 unfortunately, not even the OG Xbox.

> Just like other decompilation projects, progress is tracked by looking at the percentage of decompiled bytes

Interesting, I guess that makes sense. How do they calculate how much is matching vs non-matching, is it still just by comparing bytes?

**Comment by ethteck** [comment]
What compiler does this game use? (for the console you're decompiling it on, that is) Is it msvc targeting windows os? If someone is interested, we could try integrating it into the site, but I'd need more info before I can really say more.

Are you able to invoke it fully on the command line?

**Comment by AverseABFun-windows** [comment]
> Ahh thanks for showing how to do this. Only thing is I don't yet have a total number of functions so I can't calculate a percentage, but that shouldn't take long to get. I also wonder if there's a way to automate this, like maybe have a script on my VPS that periodically counts the number of functions in the repo and calculates the percentage.
> 
> > Also I'm working on figuring out a way to get Lego island running with wine as I have no windows computer(although I have a license and might just use a VM)
> 
> LEGO Island can be run in Wine. Just swap in the real D3DRM ([this one](https://legoisland.org/download/d3drm.zip) has the highest compatibility), and then use [Rebuilder](https://github.com/itsmattkc/legoislandrebuilder) to implement Pick()/GetPickRecords(), and it should all be playable.

Thanks! I'll have to try this in the morning.

**Comment by itsmattkc** [comment]
> What compiler does this game use? (for the console you're decompiling it on, that is) Is it msvc targeting windows os? If someone is interested, we could try integrating it into the site, but I'd need more info before I can really say more.
> 
> Are you able to invoke it fully on the command line?

Read the README

**Comment by ethteck** [comment]
Thanks for the prompt reply. I got an email that just said

> Read the README 

Sorry for not checking there first, but I'm on mobile and just saw a message on the decomp.me discord, asking me (as a maintainer) to weigh in on this thread. so I'd appreciate a little more tact if you want my help

That being said, given the contents of your edit, I think we can probably figure out how to integrate your compiler into the site if you're interested. I'll mention this in our discord

**Comment by itsmattkc** [comment]
Yes, I apologize. I was distracted and responded too quickly without thinking, I realized how it came across after sending (hence the edit). I very much appreciate you taking the time to look into this for us.

**Comment by ethteck** [comment]
Thanks :) I appreciate the apology. I'm gonna be pretty busy the next few days, but it sounds like a fun foray into adding msvc to the site!

**Comment by mkst** [comment]
decomp.me (and console game decompilation in general) is targeted towards matching decompilation - a game's binary is disassembled into assembly (which assembles back to a byte-perfect match of the original) and then functions are replaced by their (e.g.) C equivalents in a Ship of Theseus manner.

If you are not aiming for matching decompilation then decomp.me (and associated tools like asm-differ) *might* not be hugely valuable.

What is your current workflow for "matching" functions (testing functional equivalence I guess). Can you replace functions 1-by-1? I know you're using Ghidra from your YT video, but beyond that...

**Comment by itsmattkc** [comment]
Ideally I _am_ aiming for matching decompilation as much as possible. The reason I say it won't be "byte accurate" is because I feel it's very unlikely we'll be able to resolve the [SmartHeap dependency](https://github.com/isledecomp/isle#smartheap) (at least that we'll be able to track down the precise version statically linked into the game). I guess we could decompile it too, but it feels like a bit of a waste of time when it doesn't actually affect gameplay. Since it's ABI compatible with the standard malloc/free, all of the actual LEGO Island instructions can still be matched perfectly, but without SmartHeap, the final compiled executables will never be identical (won't have matching hashes, etc.)

But other than that, I'm all for matching, and generally consider a function "done" when its compiled output matches the original (essentially asm diffing but manually).

**Comment by ArjixWasTaken** [comment]
> I am not experienced with C++ or ASM in general, but is it not possible to copy the asm of the library into the build of the decompiled code?
> 
> Like, it being a build step or smth.
> Or is it that we can't do that bc the linker is not aware of it?
> 
> Just realized this would only work for win32 builds, if it even works that is.

Actually, if the binaries produced are identical other than the fact of the missing library, a delta patch could fix this, no?

**Comment by AverseABFun-windows** [comment]
> Ahh thanks for showing how to do this. Only thing is I don't yet have a total number of functions so I can't calculate a percentage, but that shouldn't take long to get. I also wonder if there's a way to automate this, like maybe have a script on my VPS that periodically counts the number of functions in the repo and calculates the percentage.
> 
> > Also I'm working on figuring out a way to get Lego island running with wine as I have no windows computer(although I have a license and might just use a VM)
> 
> LEGO Island can be run in Wine. Just swap in the real D3DRM ([this one](https://legoisland.org/download/d3drm.zip) has the highest compatibility), and then use [Rebuilder](https://github.com/itsmattkc/legoislandrebuilder) to implement Pick()/GetPickRecords(), and it should all be playable.

I tried but got a wine error:
`Unhandled exception: page fault on read access to 0x000000fd in 32-bit code (0x69ef1373).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:69ef1373 ESP:0051f890 EBP:0051f918 EFLAGS:00210246(  R- --  I  Z- -P- )
 EAX:00000000 EBX:0064a2e8 ECX:0051f890 EDX:41008000
 ESI:00000000 EDI:042a2178
Stack dump:
0x0051f890:  00000000 0051f8d8 0051f8dc 00000780
0x0051f8a0:  00000438 0000003c 00000076 00000001
0x0051f8b0:  006469a0 0051f938 0051f8f8 69ec3b80
0x0051f8c0:  006469a0 0051f938 000000a0 00000014
0x0051f8d0:  00000000 00000000 0721b34c 41008000
0x0051f8e0:  0000025f 00000001 0000026f 00000011
Backtrace:
=>0 0x69ef1373 ddraw_surface7_BltFast+0x15e(iface=<is not available>, dst_x=<is not available>, dst_y=<is not available>, src_surface=<is not available>, src_rect=042A2178, trans=<is not available>) [Z:\usr\src\packages\BUILD\dlls\ddraw\surface.c:4440] in ddraw (0x0051f918)
  1 0x69ef2504 ddraw_surface1_BltFast+0xef(iface=<couldn't compute location>, dst_x=<couldn't compute location>, dst_y=<couldn't compute location>, src_surface=<couldn't compute location>, src_rect=<couldn't compute location>, flags=<couldn't compute location>) [Z:\usr\src\packages\BUILD\dlls\ddraw\surface.c:4503] in ddraw (0x0051f978)
  2 0x1007ba8e in lego1 (+0x7ba8e) (0x0051f9fc)
  3 0x100bde6e in lego1 (+0xbde6e) (0x04292fd8)
  4 0x04293268 (0x04292ed0)
  5 0x04292fd8 (0x04295aa8)
  6 0x04292ed0 (0x04295ae0)
  7 0x04295aa8 (0x04295e08)
  8 0x04295ae0 (0x0703beb8)
  9 0x04295e08 (0x07425a88)
  10 0x0703beb8 (0x07751d80)
  11 0x07425a88 (0x07429278)
  12 0x07751d80 (0x074260f8)
  13 0x07429278 (0x04290d68)
  14 0x074260f8 (0x04290e98)
  15 0x04290d68 (0x04290f90)
  16 0x04290e98 (0x04291008)
  17 0x04290f90 (0x04292de0)
  18 0x04291008 (0x04293268)
  19 0x04292de0 (0x04292fd8)
  20 0x04293268 (0x04292ed0)
  21 0x04292fd8 (0x04295aa8)
  22 0x04292ed0 (0x04295ae0)
  23 0x04295aa8 (0x04295e08)
  24 0x04295ae0 (0x0703beb8)
  25 0x04295e08 (0x07425a88)
  26 0x0703beb8 (0x07751d80)
  27 0x07425a88 (0x07429278)
  28 0x07751d80 (0x074260f8)
  29 0x07429278 (0x04290d68)
  30 0x074260f8 (0x04290e98)
  31 0x04290d68 (0x04290f90)
  32 0x04290e98 (0x04291008)
  33 0x04290f90 (0x04292de0)
  34 0x04291008 (0x04293268)
  35 0x04292de0 (0x04292fd8)
  36 0x04293268 (0x04292ed0)
  37 0x04292fd8 (0x04295aa8)
  38 0x04292ed0 (0x04295ae0)
  39 0x04295aa8 (0x04295e08)
  40 0x04295ae0 (0x0703beb8)
  41 0x04295e08 (0x07425a88)
  42 0x0703beb8 (0x07751d80)
  43 0x07425a88 (0x07429278)
  44 0x07751d80 (0x074260f8)
  45 0x07429278 (0x04290d68)
  46 0x074260f8 (0x04290e98)
  47 0x04290d68 (0x04290f90)
  48 0x04290e98 (0x04291008)
  49 0x04290f90 (0x04292de0)
  50 0x04291008 (0x04293268)
  51 0x04292de0 (0x04292fd8)
  52 0x04293268 (0x04292ed0)
  53 0x04292fd8 (0x04295aa8)
  54 0x04292ed0 (0x04295ae0)
  55 0x04295aa8 (0x04295e08)
  56 0x04295ae0 (0x0703beb8)
  57 0x04295e08 (0x07425a88)
  58 0x0703beb8 (0x07751d80)
  59 0x07425a88 (0x07429278)
  60 0x07751d80 (0x074260f8)
  61 0x07429278 (0x04290d68)
  62 0x074260f8 (0x04290e98)
  63 0x04290d68 (0x04290f90)
  64 0x04290e98 (0x04291008)
  65 0x04290f90 (0x04292de0)
  66 0x04291008 (0x04293268)
  67 0x04292de0 (0x04292fd8)
  68 0x04293268 (0x04292ed0)
  69 0x04292fd8 (0x04295aa8)
  70 0x04292ed0 (0x04295ae0)
  71 0x04295aa8 (0x04295e08)
  72 0x04295ae0 (0x0703beb8)
  73 0x04295e08 (0x07425a88)
  74 0x0703beb8 (0x07751d80)
  75 0x07425a88 (0x07429278)
  76 0x07751d80 (0x074260f8)
  77 0x07429278 (0x04290d68)
  78 0x074260f8 (0x04290e98)
  79 0x04290d68 (0x04290f90)
  80 0x04290e98 (0x04291008)
  81 0x04290f90 (0x04292de0)
  82 0x04291008 (0x04293268)
  83 0x04292de0 (0x04292fd8)
  84 0x04293268 (0x04292ed0)
  85 0x04292fd8 (0x04295aa8)
  86 0x04292ed0 (0x04295ae0)
  87 0x04295aa8 (0x04295e08)
  88 0x04295ae0 (0x0703beb8)
  89 0x04295e08 (0x07425a88)
  90 0x0703beb8 (0x07751d80)
  91 0x07425a88 (0x07429278)
  92 0x07751d80 (0x074260f8)
  93 0x07429278 (0x04290d68)
  94 0x074260f8 (0x04290e98)
  95 0x04290d68 (0x04290f90)
  96 0x04290e98 (0x04291008)
  97 0x04290f90 (0x04292de0)
  98 0x04291008 (0x04293268)
  99 0x04292de0 (0x04292fd8)
  100 0x04293268 (0x04292ed0)
  101 0x04292fd8 (0x04295aa8)
  102 0x04292ed0 (0x04295ae0)
  103 0x04295aa8 (0x04295e08)
  104 0x04295ae0 (0x0703beb8)
  105 0x04295e08 (0x07425a88)
  106 0x0703beb8 (0x07751d80)
  107 0x07425a88 (0x07429278)
  108 0x07751d80 (0x074260f8)
  109 0x07429278 (0x04290d68)
  110 0x074260f8 (0x04290e98)
  111 0x04290d68 (0x04290f90)
  112 0x04290e98 (0x04291008)
  113 0x04290f90 (0x04292de0)
  114 0x04291008 (0x04293268)
  115 0x04292de0 (0x04292fd8)
  116 0x04293268 (0x04292ed0)
  117 0x04292fd8 (0x04295aa8)
  118 0x04292ed0 (0x04295ae0)
  119 0x04295aa8 (0x04295e08)
  120 0x04295ae0 (0x0703beb8)
  121 0x04295e08 (0x07425a88)
  122 0x0703beb8 (0x07751d80)
  123 0x07425a88 (0x07429278)
  124 0x07751d80 (0x074260f8)
  125 0x07429278 (0x04290d68)
  126 0x074260f8 (0x04290e98)
  127 0x04290d68 (0x04290f90)
  128 0x04290e98 (0x04291008)
  129 0x04290f90 (0x04292de0)
  130 0x04291008 (0x04293268)
  131 0x04292de0 (0x04292fd8)
  132 0x04293268 (0x04292ed0)
  133 0x04292fd8 (0x04295aa8)
  134 0x04292ed0 (0x04295ae0)
  135 0x04295aa8 (0x04295e08)
  136 0x04295ae0 (0x0703beb8)
  137 0x04295e08 (0x07425a88)
  138 0x0703beb8 (0x07751d80)
  139 0x07425a88 (0x07429278)
  140 0x07751d80 (0x074260f8)
  141 0x07429278 (0x04290d68)
  142 0x074260f8 (0x04290e98)
  143 0x04290d68 (0x04290f90)
  144 0x04290e98 (0x04291008)
  145 0x04290f90 (0x04292de0)
  146 0x04291008 (0x04293268)
  147 0x04292de0 (0x04292fd8)
  148 0x04293268 (0x04292ed0)
  149 0x04292fd8 (0x04295aa8)
  150 0x04292ed0 (0x04295ae0)
  151 0x04295aa8 (0x04295e08)
  152 0x04295ae0 (0x0703beb8)
  153 0x04295e08 (0x07425a88)
  154 0x0703beb8 (0x07751d80)
  155 0x07425a88 (0x07429278)
  156 0x07751d80 (0x074260f8)
  157 0x07429278 (0x04290d68)
  158 0x074260f8 (0x04290e98)
  159 0x04290d68 (0x04290f90)
  160 0x04290e98 (0x04291008)
  161 0x04290f90 (0x04292de0)
  162 0x04291008 (0x04293268)
  163 0x04292de0 (0x04292fd8)
  164 0x04293268 (0x04292ed0)
  165 0x04292fd8 (0x04295aa8)
  166 0x04292ed0 (0x04295ae0)
  167 0x04295aa8 (0x04295e08)
  168 0x04295ae0 (0x0703beb8)
  169 0x04295e08 (0x07425a88)
  170 0x0703beb8 (0x07751d80)
  171 0x07425a88 (0x07429278)
  172 0x07751d80 (0x074260f8)
  173 0x07429278 (0x04290d68)
  174 0x074260f8 (0x04290e98)
  175 0x04290d68 (0x04290f90)
  176 0x04290e98 (0x04291008)
  177 0x04290f90 (0x04292de0)
  178 0x04291008 (0x04293268)
  179 0x04292de0 (0x04292fd8)
  180 0x04293268 (0x04292ed0)
  181 0x04292fd8 (0x04295aa8)
  182 0x04292ed0 (0x04295ae0)
  183 0x04295aa8 (0x04295e08)
  184 0x04295ae0 (0x0703beb8)
  185 0x04295e08 (0x07425a88)
  186 0x0703beb8 (0x07751d80)
  187 0x07425a88 (0x07429278)
  188 0x07751d80 (0x074260f8)
  189 0x07429278 (0x04290d68)
  190 0x074260f8 (0x04290e98)
  191 0x04290d68 (0x04290f90)
  192 0x04290e98 (0x04291008)
  193 0x04290f90 (0x04292de0)
  194 0x04291008 (0x04293268)
  195 0x04292de0 (0x04292fd8)
  196 0x04293268 (0x04292ed0)
  197 0x04292fd8 (0x04295aa8)
  198 0x04292ed0 (0x04295ae0)
  199 0x04295aa8 (0x04295e08)
  200 0x04295ae0 (0x0703beb8)
0x69ef1373 ddraw_surface7_BltFast+0x15e [Z:\usr\src\packages\BUILD\dlls\ddraw\surface.c:4440] in ddraw: testb	$0x2,0xfd(%esi)
Unable to access file 'Z:\usr\src\packages\BUILD\dlls\ddraw\surface.c'
Modules:
Module	Address			Debug info	Name (136 modules)
PE	00370000-003d7000	Deferred        msvfw32
PE	00400000-0041a000	Deferred        isle
PE	00820000-00c99000	Deferred        ole32
PE	00ca0000-00eb3000	Deferred        rpcrt4
PE	00ec0000-01345000	Deferred        comctl32
PE	01350000-026e4000	Deferred        wined3d
PE	03270000-032f4000	Deferred        winex11
PE	048e0000-04906000	Deferred        rebld
PE	04910000-04a09000	Deferred        shlwapi
PE	04c10000-04ca4000	Deferred        mmdevapi
PE	10000000-10121000	Export          lego1
ELF	5da55000-62500000	Deferred        libllvm-11.so.1
PE	62500000-6290a000	Deferred        oleaut32
PE	63e40000-63ebb000	Deferred        winepulse
PE	64a80000-64ad8000	Deferred        win32u
PE	65680000-656c6000	Deferred        msvcrt
PE	66080000-660e2000	Deferred        msacm32
PE	66640000-6665a000	Deferred        version
PE	667c0000-66805000	Deferred        shcore
PE	67500000-67553000	Deferred        imm32
PE	67c00000-67d37000	Deferred        dsound
PE	684c0000-6860d000	Deferred        combase
PE	68880000-68d6b000	Deferred        user32
PE	69840000-6993b000	Deferred        advapi32
PE	69ec0000-6a11f000	Dwarf-4         ddraw
PE	6aac0000-6ad9e000	Deferred        ucrtbase
PE	6aec0000-6b06f000	Deferred        setupapi
PE	6bbc0000-6bc57000	Deferred        sechost
PE	6da80000-6dca0000	Deferred        gdi32
PE	6dd90000-6ddea000	Deferred        d3drm
PE	6de80000-6df73000	Deferred        dinput
PE	6f240000-6f3bc000	Deferred        winmm
ELF	705bd000-70d80000	Deferred        libvulkan_radeon.so
PE	70d80000-70e20000	Deferred        uxtheme
PE	71080000-710a8000	Deferred        hid
PE	71400000-720af000	Deferred        shell32
ELF	72dba000-74808000	Deferred        virtio_gpu_dri.so
ELF	748ee000-74fcb000	Deferred        libvulkan_lvp.so
ELF	74fcb000-76800000	Deferred        libz3.so.4
PE	7a800000-7acc1000	Deferred        opengl32
PE	7b000000-7b52c000	Deferred        kernelbase
PE	7b600000-7b759000	Deferred        kernel32
ELF	7b879000-7b88e000	Deferred        libnss_files.so.2
ELF	7b88e000-7b89a000	Deferred        libdrm_nouveau.so.2
ELF	7b89a000-7b912000	Deferred        libglx_mesa.so.0
ELF	7b912000-7b98f000	Deferred        libgldispatch.so.0
ELF	7bb93000-7bc00000	Deferred        libgl.so.1
PE	7bc00000-7bebc000	Deferred        ntdll
ELF	7bebd000-7becc000	Deferred        libdrm_radeon.so.1
ELF	7becc000-7bedd000	Deferred        libsensors.so.5
ELF	7bedd000-7bee7000	Deferred        libxcb-xfixes.so.0
ELF	7bee7000-7beec000	Deferred        libxcb-shm.so.0
ELF	7c408000-7c479000	Deferred        libvklayer_mesa_device_select.so
ELF	7c479000-7ceb0000	Deferred        libvulkan_intel.so
ELF	7d000000-7d005000	Deferred        <wine-loader>
ELF	7d005000-7d00c000	Deferred        libxcb-dri2.so.0
ELF	7d00c000-7d035000	Deferred        libglapi.so.0
ELF	7d406000-7d442000	Deferred        libglx.so.0
ELF	7d442000-7d46b000	Deferred        libtinfo.so.6
ELF	7d46b000-7d4a3000	Deferred        libedit.so.2
ELF	7d4a3000-7d4ad000	Deferred        libatomic.so.1
ELF	7d4ad000-7d4b7000	Deferred        libffi.so.7
ELF	7d4b7000-7d4d5000	Deferred        libxcb-glx.so.0
ELF	7d546000-7d564000	Deferred        libelf.so.1
ELF	7d564000-7d571000	Deferred        libdrm_amdgpu.so.1
ELF	7d571000-7d585000	Deferred        libxcb-randr.so.0
ELF	7d585000-7d58e000	Deferred        libxcb-sync.so.1
ELF	7d59e000-7d600000	Deferred        libvulkan.so.1
ELF	7d703000-7d708000	Deferred        libxcb-present.so.0
ELF	7d708000-7d721000	Deferred        libdrm.so.2
ELF	7d721000-7d740000	Deferred        libgcc_s.so.1
ELF	7d744000-7d754000	Deferred        libwayland-client.so.0
ELF	7d756000-7d75e000	Deferred        libkeyutils.so.1
ELF	7d75e000-7d76e000	Deferred        libkrb5support.so.0
ELF	7d76e000-7d773000	Deferred        libcom_err.so.2
ELF	7d773000-7d7a6000	Deferred        libk5crypto.so.3
ELF	7d7a6000-7d882000	Deferred        libkrb5.so.3
ELF	7d882000-7d8dc000	Deferred        libgssapi_krb5.so.2
ELF	7d8dc000-7d911000	Deferred        libtirpc.so.3
ELF	7d911000-7d939000	Deferred        libgpg-error.so.0
ELF	7d939000-7d953000	Deferred        libresolv.so.2
ELF	7d953000-7d95f000	Deferred        libogg.so.0
ELF	7d95f000-7d9bc000	Deferred        libopus.so.0
ELF	7d9bc000-7da49000	Deferred        libvorbisenc.so.2
ELF	7da49000-7da75000	Deferred        libvorbis.so.0
ELF	7da75000-7dab0000	Deferred        libflac.so.8
ELF	7dab0000-7dacb000	Deferred        libnsl.so.2
ELF	7dacb000-7dbb2000	Deferred        libgcrypt.so.20
ELF	7dbb2000-7dbd6000	Deferred        liblz4.so.1
ELF	7dbd6000-7dca7000	Deferred        libzstd.so.1
ELF	7dca7000-7dcd3000	Deferred        liblzma.so.5
ELF	7dcd3000-7dcdf000	Deferred        librt.so.1
ELF	7dcdf000-7dd77000	Deferred        libsndfile.so.1
ELF	7dd77000-7de37000	Deferred        libsystemd.so.0
ELF	7de37000-7de99000	Deferred        libdbus-1.so.3
ELF	7de99000-7df27000	Deferred        libpulsecommon-14.2.so
ELF	7df27000-7df85000	Deferred        libpulse.so.0
ELF	7df86000-7df89000	Deferred        libxshmfence.so.1
ELF	7df89000-7df8e000	Deferred        libx11-xcb.so.1
ELF	7df8e000-7df94000	Deferred        libxcb-dri3.so.0
ELF	7df9b000-7dfb0000	Deferred        winepulse.so
ELF	7dfb0000-7e052000	Deferred        opengl32.so
ELF	7e13d000-7e145000	Deferred        libxfixes.so.3
ELF	7e145000-7e152000	Deferred        libxcursor.so.1
ELF	7e152000-7e166000	Deferred        libxi.so.6
ELF	7e166000-7e16b000	Deferred        libxcomposite.so.1
ELF	7e16b000-7e178000	Deferred        libxrandr.so.2
ELF	7e178000-7e184000	Deferred        libxrender.so.1
ELF	7e184000-7e18b000	Deferred        libxxf86vm.so.1
ELF	7e18b000-7e190000	Deferred        libxinerama.so.1
ELF	7e190000-7e19f000	Deferred        libmd.so.0
ELF	7e19f000-7e1b7000	Deferred        libbsd.so.0
ELF	7e1b7000-7e1be000	Deferred        libxdmcp.so.6
ELF	7e1be000-7e1c3000	Deferred        libxau.so.6
ELF	7e1c3000-7e1f1000	Deferred        libxcb.so.1
ELF	7e1f1000-7e343000	Deferred        libx11.so.6
ELF	7e343000-7e359000	Deferred        libxext.so.6
ELF	7e359000-7e361000	Deferred        libasyncns.so.0
ELF	7e361000-7e36d000	Deferred        libwrap.so.0
ELF	7e36f000-7e3fc000	Deferred        winex11.so
ELF	7e56f000-7e59d000	Deferred        libexpat.so.1
ELF	7e59d000-7e5ea000	Deferred        libfontconfig.so.1
ELF	7e5ea000-7e60d000	Deferred        libbrotlicommon.so.1
ELF	7e60d000-7e61b000	Deferred        libbrotlidec.so.1
ELF	7e61b000-7e639000	Deferred        libz.so.1
ELF	7e639000-7e679000	Deferred        libpng16.so.16
ELF	7e679000-7e77d000	Deferred        libm.so.6
ELF	7e77d000-7e8f1000	Deferred        win32u.so
ELF	7e8f1000-7ea7a000	Dwarf           libwine.so.1
ELF	7ea9f000-7eaa9000	Deferred        libuuid.so.1
ELF	7eaa9000-7eb70000	Deferred        libfreetype.so.6
ELF	f4dd9000-f4e8a000	Deferred        ntdll.so
ELF	f4e8a000-f5072000	Deferred        libc.so.6
ELF	f5072000-f5078000	Deferred        libdl.so.2
ELF	f5078000-f509a000	Deferred        libpthread.so.0
ELF	f50b2000-f50de000	Deferred        ld-linux.so.2
Threads:
process  tid      prio    name (all IDs are in hex)
00000020 Rebuilder.exe
	00000024    0     
	000001c8    0     
00000038 services.exe
	0000003c    0     
	00000040    0     wine_rpcrt4_server
	0000004c    0     wine_rpcrt4_io
	0000005c    0     wine_rpcrt4_io
	00000074    0     wine_rpcrt4_io
	00000094    0     wine_rpcrt4_io
	000000c4    0     wine_rpcrt4_io
	000000e8    0     wine_rpcrt4_io
00000044 winedevice.exe
	00000048    0     
	00000054    0     
	00000058    0     wine_sechost_service
	00000060    0     
	00000064    0     
	00000068    0     
	000000d0    0     
0000006c winedevice.exe
	00000070    0     
	00000078    0     
	0000007c    0     wine_sechost_service
	00000080    0     
	00000084    0     
	00000088    0     
	000000a8    0     
	000000b8    0     
0000008c plugplay.exe
	00000090    0     
	000000a0    0     
	000000a4    0     wine_sechost_service
	000000ac    0     wine_rpcrt4_server
	000000bc    0     wine_rpcrt4_io
00000098 explorer.exe
	0000009c    0     
	000000d4    0     
	000000d8    0     wine_rpcrt4_server
000000b0 svchost.exe
	000000b4    0     
	000000c8    0     
	000000cc    0     wine_sechost_service
000000e0 rpcss.exe
	000000e4    0     
	000000f0    0     
	000000f4    0     wine_sechost_service
	000000f8    0     wine_rpcrt4_server
	000000fc    0     wine_rpcrt4_server
	00000100    0     wine_rpcrt4_io
00000108 conhost.exe
	0000010c    0     
000001c0 (D) Z:\home\arthur\LEGO Island\ISLE.EXE
	000001c4    0 <== 
	000001cc   15     winepulse_mainloop
	000001dc   15     winepulse_timer_loop
	000001e0   15     wine_dsound_mixer
	000001e8    0     wined3d_cs
	000001ec    0     
	000001fc    0     
	00000208    0     
System information:
    Wine build: wine-8.0.1
    Platform: i386 (WOW64)
    Version: Windows 7
    Host system: Linux
    Host version: 5.15.112-19373-g62629859bf76`

**Comment by ItsRemix** [comment]
> Here's the script that's used for the progress; https://github.com/open-ead/nx-decomp-tools/blob/master/progress.py.
> 
> Per [this commit](https://github.com/zeldaret/botw/commit/9e3975a813baf0727f17f02cc1d7a17a15a30db9):
> 
> > Just like other decompilation projects, progress is tracked by looking at the percentage of decompiled bytes (the number of decompiled bytes divided by the total code size).

This code is not fully available, They dont have config which is readed in a weird way I say but if we gett full size of Lego Island and try comparing it, I can create full website like this.

**Comment by ItsRemix** [comment]
I did basic progress bar which is based on github's REST api and fetches latest DLL build, gets its size and compares to total size of dll

**Comment by ItsRemix** [comment]
I did basic progress bar which is based on github's REST api and fetches latest DLL build, gets its size and compares to total size of dll 

Site: https://lego.remix.ovh/progress
Repo: https://github.com/ItsRemix/lego-island-decomp-www

**Comment by ArjixWasTaken** [comment]
> Ahh thanks for showing how to do this. Only thing is I don't yet have a total number of functions so I can't calculate a percentage, but that shouldn't take long to get. I also wonder if there's a way to automate this, like maybe have a script on my VPS that periodically counts the number of functions in the repo and calculates the percentage.

PS: You can set a github action to run at an interval

[Example workflow that runs every 15 minutes](https://github.com/ArjixWasTaken/anime-rss/blob/main/.github/workflows/generate-rss.yml#L6)

Open source repositories have no restriction on how much the workflow runs.
(Other than the hard limit of 6 hours per run)

**Comment by ItsRemix** [comment]
If you get any idea how to do that I could add it to the unofficial site

**Comment by mkst** [comment]
The job only needs to run when a commit is pushed/merged to the main branch, you don't need to be continually running something, unless I'm missing something?

**Pull request closed without merging**
